#pragma once
#include <QWidget>
#include <AIS_InteractiveContext.hxx>
#include <V3d_View.hxx>
#include <TopoDS_Shape.hxx>
#include <memory>

/// Primary OpenCascade 3D viewport.
/// Supports dynamic model display, pan/zoom/rotate, and analysis overlays.
class OccView : public QWidget
{
    Q_OBJECT
public:
    explicit OccView(QWidget* parent = nullptr);
    ~OccView() override;

    /// Display a shape in the viewport (clears old contents)
    void displayShape(const TopoDS_Shape& shape, const QColor& color = Qt::lightGray);

    /// Show FEA/analysis results (mapped via color fields)
    void showAnalysisResults(const QString& dataPath);

public slots:
    /// Loads a BREP file generated by reverse engineering or import
    void loadBrepModel(const QString& brepPath);

protected:
    void paintEvent(QPaintEvent*) override;
    void resizeEvent(QResizeEvent*) override;
    void wheelEvent(QWheelEvent* e) override;
    void mousePressEvent(QMouseEvent* e) override;
    void mouseMoveEvent(QMouseEvent* e) override;

private:
    Handle(AIS_InteractiveContext) m_context;
    Handle(V3d_View) m_view;
    QPoint m_lastMousePos;
};
